### ISSUE TITLE
Extend the theme to error message

### ISSUE THREAD

**Issue by AdelQasem** [undiabler/nord-rofi-theme#5]
Currently, when showing an error (e.g., no such file or directory), the error text is shown by itself, not over a Nord-themed box or anything. Would be nice if the theme was extended to include error windows. Thanks!

**Comment by nagarutu** [comment]
I like this theme and figured id wake up this 2 year old issue.

Here's a basic text box to add to the nord.config that will make a  error box

```yaml
textbox {
    padding: 8px;
    border-radius: 6px 6px 6px 6px;
    border-color: @nord10;
    border: 1px 1px 1px 1px;
    background-color: rgba(46,52,64,0.9);
    dynamic: true;
    text-color: @backlight;
}
```
